before_script:
  - wget -N http://buildboost.org/build.xml
  
jdk:
  - openjdk7
#  - openjdk7
#  - oraclejdk6
#  - oraclejdk7
  
language: java
script: "ant -DrootRepository='git:https://github.com/FunThomas424242/devtools.git'"